apiVersion: v1
kind: Service
metadata:
  name: ofan-valheim-service
spec:
  type: NodePort
  selector:
    app: ofan-valheim
  ports:
    - name: valheim-udp
      protocol: UDP
      port: 2456
      targetPort: 2456
      nodePort: 32456
    - name: valheim-query
      protocol: UDP
      port: 2457
      targetPort: 2457
      nodePort: 32457
